In [1]:
from pyforest import * 
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.neighbors import KNeighborsClassifier


# Sample Data

In [3]:
# sample text data
sample_train=['i will call you tonight','please help me...','please call a cab please !']

In [4]:
# sample target vector
y=[0,1,0]    #0~Ham, 1~Spam.

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
toNumeric = CountVectorizer()

In [6]:
# get the vocabulary (unique words) from training data
toNumeric.fit(sample_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [7]:
toNumeric.get_feature_names()

['cab', 'call', 'help', 'me', 'please', 'tonight', 'will', 'you']

In [8]:
sample_train=['i will call you tonight','please help me...','please call a cab please !']

In [9]:
# convert training data into a 'document term matrix.
sample_train_dtm= toNumeric.transform(sample_train)
sample_train_dtm   # it creats sparse matrix.

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [10]:
#lets convert sparse matrix to a dense matrix.
sample_train_dtm.toarray()

array([[0, 1, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 2, 0, 0, 0]], dtype=int64)

In [11]:
pd.DataFrame(sample_train_dtm.toarray(), columns=toNumeric.get_feature_names())

cab  call  help  me  please  tonight  will  you
0    0     1     0   0       0        1     1    1
1    0     0     1   1       1        0     0    0
2    1     1     0   0       2        0     0    0

In [13]:
# build a model to predict the target variable
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(sample_train_dtm,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [14]:
# Sample test for model validation
sampleTest=["Don't call please"] 

In order to make a prediction, the new test data must have the same featurs as training observation, both in number and meaning.

In [15]:
# transform test data into DTM by using generated vocabulary
sample_test_dtm = toNumeric.transform(sampleTest)
sample_test_dtm.toarray()

array([[0, 1, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [16]:
# test build model
knn.predict(sample_test_dtm)

array([0])

**SUMMARY**

- `toNumeric.fit(sample_train)` **learn the vocabulary** from training data.
- `toNumeric.transform(sample_train)` use the **trained vocabulary** to build DTM from the train data.
- `toNumeric.transform(sampleTest)` use the **trained vocabulary** to build DTM from the test data and **ignor vocabulary** it hasn't seed before.