In [2]:
from pyforest import * 
import warnings
warnings.filterwarnings("ignore")

In [3]:
from sklearn.neighbors import KNeighborsClassifier


# Sample Data

In [4]:
# sample text data
sample_train=['i will call you tonight','please help me...','please call a cab please !']

In [5]:
# sample target vector
y=[0,1,0]    #0~Ham, 1~Spam.

In [6]:
#from sklearn.feature_extraction.text import CountVectorizer
#toNumeric = CountVectorizer()

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
toNumericTFIDF = TfidfVectorizer()

In [9]:
toNumericTFIDF.fit(sample_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [10]:
toNumericTFIDF.get_feature_names()

['cab', 'call', 'help', 'me', 'please', 'tonight', 'will', 'you']

In [12]:
sample_trainTFIDF_dtm = toNumericTFIDF.transform(sample_train)

In [13]:
sample_trainTFIDF_dtm

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [14]:
sample_trainTFIDF_dtm.toarray()

array([[0.        , 0.40204024, 0.        , 0.        , 0.        ,
        0.52863461, 0.52863461, 0.52863461],
       [0.        , 0.        , 0.62276601, 0.62276601, 0.4736296 ,
        0.        , 0.        , 0.        ],
       [0.50689001, 0.38550292, 0.        , 0.        , 0.77100584,
        0.        , 0.        , 0.        ]])

In [15]:
pd.DataFrame(sample_trainTFIDF_dtm.toarray(), columns=toNumericTFIDF.get_feature_names())

cab      call      help        me    please   tonight      will  \
0  0.00000  0.402040  0.000000  0.000000  0.000000  0.528635  0.528635   
1  0.00000  0.000000  0.622766  0.622766  0.473630  0.000000  0.000000   
2  0.50689  0.385503  0.000000  0.000000  0.771006  0.000000  0.000000   

        you  
0  0.528635  
1  0.000000  
2  0.000000

In [16]:
sample_train

['i will call you tonight', 'please help me...', 'please call a cab please !']

In [18]:
# build a model to predict the target variable
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(sample_trainTFIDF_dtm,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [19]:
# Sample test for model validation
sampleTest=["Don't call please"] 

In order to make a prediction, the new test data must have the same featurs as training observation, both in number and meaning.

In [21]:
# transform test data into DTM by using generated vocabulary
sample_test_dtm = toNumericTFIDF.transform(sampleTest)
sample_test_dtm.toarray()

array([[0.        , 0.70710678, 0.        , 0.        , 0.70710678,
        0.        , 0.        , 0.        ]])

In [22]:
# test build model
knn.predict(sample_test_dtm)

array([0])

**SUMMARY**

- `toNumeric.fit(sample_train)` **learn the vocabulary** from training data.
- `toNumeric.transform(sample_train)` use the **trained vocabulary** to build DTM from the train data.
- `toNumeric.transform(sampleTest)` use the **trained vocabulary** to build DTM from the test data and **ignor vocabulary** it hasn't seed before.